# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nick Lewis
email: nickeblewis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Making sense of the modern web and helping you get the best out of it.
  We cover a lot of JavaScript, Ruby, HTML and CSS topics.
  Teaching people both new and well acquainted to Coding through online
  and one-to-one tutorials using our tutl.io system.
  This website is proudly built on Jekyll :-)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://headforcode.com" # the base hostname & protocol for your site
twitter_username: nicklewis
github_username:  nickeblewis

# Build settings
markdown: kramdown
